### ISSUE TITLE
SevenZipExtractor.SevenZipException: '7z.dll not found'

### ISSUE THREAD

**Issue by tal12345** [adoconnection/SevenZipExtractor#30]
SevenZipExtractor.SevenZipException
  HResult=0x80131500
  Message=7z.dll not found
  Source=SevenZipExtractor
  StackTrace:
   at SevenZipExtractor.ArchiveFile.InitializeAndValidateLibrary()
   at SevenZipExtractor.ArchiveFile..ctor(Stream archiveStream, Nullable`1 format, String libraryFilePath)
   at ConsoleApplication87.Program.Main(String[] args) in C:\temp\Zip\SevenZipExtractor-master\SevenZipExtractor-master\Benchmark\Program.cs:line 75

Do you know what is missing? where?

**Comment by adoconnection** [comment]
I think its just benchmark app is outdated :(

**Comment by adoconnection** [comment]
@WojciechNagorski did new benchamark app.
